---
deployment:
  tasks:
    - export DEPLOYPATH=/home/revelr5/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp contactme.html $DEPLOYPATH